ARG GIT_VERSION
ARG DOCKER_CLI_VERSION=dev
ARG OS=anolis

FROM kubernetesloong64/git-loong64:${GIT_VERSION}-${OS} AS git-stage
FROM kubernetesloong64/docker-cli-loong64:${DOCKER_CLI_VERSION}-${OS}

COPY --from=git-stage /usr/local /usr/local

RUN git --version
