ARG GIT_VERSION
ARG DOCKER_CLI_VERSION=dev
ARG OS=debian

FROM kubernetesloong64/git-loong64:${GIT_VERSION}-${OS} AS git-stage
FROM kubernetesloong64/docker-cli-loong64:${DOCKER_CLI_VERSION}-${OS}

COPY --from=git-stage /usr/local /usr/local

RUN apt-get update \
    && apt-get install -y --no-install-recommends libcurl4-gnutls ca-certificates \
    && git --version \
    && git clone https://github.com/kubernetes-loong64/git-loong64.git /tmp/git-loong64 \
    && rm -rf /tmp/git-loong64
